pipeline {
   agent any
    environment {
      RELEASE='20.04'
    }
   stages {
      stage('Build') {
            environment {
               LOG_LEVEL='INFO'
            }
            steps {
               echo "Building release ${RELEASE} with log level ${LOG_LEVEL}..."
            }
        }
        stage('Test') {
            steps {
               echo "Testing release ${RELEASE}"
               writeFile file: 'test-results.txt', text: 'passed'      
                withCredentials([string(credentialsId: 'slack-token', variable: 'API_KEY')]) {
                 echo "Using key ${API_KEY}"
               }         
            }
        }
   }
   post {
      success {
         archiveArtifacts 'test-results.txt'
         slackSend channel: '#builds',
                   message: "Release ${env.RELEASE}, success: ${currentBuild.fullDisplayName}."
      }
   }
}