library identifier: 'shared-pipeline@master', 
        retriever: modernSCM([$class: 'GitSCMSource',
        credentialsId: 'githubcred',
        remote: 'https://github.com/imadi/jenkins-pipeline-samples.git'])

pipeline {
    agent any
    stages {
        stage('Audit tools') {                        
            steps {
                auditTools()
            }
        }
    }
}
