library identifier: 'shared@master', 
        retriever: modernSCM([$class: 'GitSCMSource', remote: 'https://github.com/imadi/jenkins-pipeline-samples.git'])

pipeline {
    agent any
    stages {
        stage('Audit tools') {                        
            steps {
                auditTools()
            }
        }
    }
}
